from __future__ import annotations
import json
from pathlib import Path
from sonic_xrpl.xaman_governance_resolution_evidence_closure_spec.models import ClosureEvidenceRecord,XamanGovernanceResolutionEvidenceClosureFixtureInput

def _load_closure_record(row:dict)->ClosureEvidenceRecord:
    return ClosureEvidenceRecord(row['closure_evidence_id'],row['closure_domain'],row.get('related_resolution_record_id',''),row.get('related_response_record_id',''),row.get('related_digest_id',''),row.get('related_snapshot_id',''),row.get('related_checklist_item_id',''),row.get('related_approval_packet_id',''),tuple(row.get('related_support_artifact_ids',[])),row.get('owner_role',''),row.get('reviewer_role',''),row.get('evidence_category','DOCUMENTATION_EVIDENCE'),row.get('evidence_status','CLOSURE_EVIDENCE_NOT_STARTED'),row.get('evidence_sufficiency_status','REVIEW_REQUIRED'),row.get('evidence_summary',''),tuple(row.get('source_evidence_references',[])),tuple(row.get('unresolved_blocker_references',[])),tuple(row.get('unresolved_limitation_references',[])),bool(row.get('non_authorization_confirmation',False)),row.get('closure_condition','NO_RUNTIME_ACTION'),row.get('deferral_reason',''),row.get('rejection_reason',''),row.get('superseded_by_closure_evidence_id',''),row.get('severity','MEDIUM'),row.get('limitation_notes',''),tuple(row.get('safety_flags',[])))

def load_xaman_governance_resolution_evidence_closure_fixture(path:str|Path)->XamanGovernanceResolutionEvidenceClosureFixtureInput:
    p=Path(path); data=json.loads(p.read_text(encoding='utf-8')); records=tuple(_load_closure_record(i) for i in data.get('closure_evidence_records',[]))
    return XamanGovernanceResolutionEvidenceClosureFixtureInput(data['fixture_id'],data['closure_bundle_id'],data['source_resolution_register_id'],data['source_response_bundle_id'],data.get('deterministic_timestamp','1970-01-01T00:00:00Z'),data.get('resolution_register_classification','RESOLUTION_REGISTER_REVIEW_REQUIRED'),data.get('response_classification','RESPONSE_BUNDLE_REVIEW_REQUIRED'),records,tuple(data.get('non_authorization_notices',[])),bool(data.get('missing_closure_evidence',False)),bool(data.get('incomplete_closure_evidence',False)),bool(data.get('rejected_closure_evidence_unresolved',False)),bool(data.get('deferred_closure_without_limitation',False)),bool(data.get('superseded_closure_missing_replacement',False)),bool(data.get('missing_non_authorization_confirmation',False)),bool(data.get('missing_owner',False)),bool(data.get('missing_reviewer',False)),bool(data.get('missing_source_evidence_reference',False)),bool(data.get('unresolved_blocker_lacks_closure_evidence',False)),bool(data.get('unresolved_limitation_lacks_closure_evidence',False)),bool(data.get('stale_evidence_closure_unresolved',False)),bool(data.get('redacted_evidence_closure_unresolved',False)),bool(data.get('reference_only_evidence_closure_unresolved',False)),bool(data.get('synthetic_only_evidence_closure_unresolved',False)),bool(data.get('dependency_audit_closure_unresolved',False)),bool(data.get('safety_review_closure_unresolved',False)),bool(data.get('traceability_gap',False)),bool(data.get('invalid_xaman_payload_approval_marker',False)),bool(data.get('invalid_wallet_material_approval_marker',False)),bool(data.get('invalid_signing_submission_autofill_approval_marker',False)),bool(data.get('invalid_testnet_live_execution_approval_marker',False)),bool(data.get('invalid_runtime_closure_service_marker',False)),bool(data.get('invalid_download_service_marker',False)),bool(data.get('invalid_api_ui_closure_route_marker',False)),bool(data.get('invalid_safety_bypass_marker',False)))
