"""SQLModel database models."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from sqlmodel import Field, SQLModel


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


# ── Token ─────────────────────────────────────────────────────────────────────

class Token(SQLModel, table=True):
    """Represents a token / currency pair seen on the XRPL."""

    id: Optional[int] = Field(default=None, primary_key=True)
    currency: str = Field(index=True)
    issuer: str = Field(index=True)
    first_seen: datetime = Field(default_factory=_utcnow)
    last_price_xrp: Optional[float] = Field(default=None)
    metadata_json: Optional[str] = Field(default=None)


# ── Signal ────────────────────────────────────────────────────────────────────

class Signal(SQLModel, table=True):
    """A trading signal generated by a strategy."""

    id: Optional[int] = Field(default=None, primary_key=True)
    request_id: str = Field(index=True)
    strategy_name: str = Field(index=True)
    currency: str
    issuer: str
    direction: str  # "BUY" | "SELL"
    price_xrp: float
    confidence: float = Field(default=1.0)
    created_at: datetime = Field(default_factory=_utcnow)
    metadata_json: Optional[str] = Field(default=None)


# ── PaperTrade ────────────────────────────────────────────────────────────────

class PaperTrade(SQLModel, table=True):
    """A simulated (paper) trade entry."""

    id: Optional[int] = Field(default=None, primary_key=True)
    request_id: str = Field(index=True)
    signal_id: Optional[int] = Field(default=None, foreign_key="signal.id")
    currency: str
    issuer: str
    direction: str  # "BUY" | "SELL"
    entry_price_xrp: float
    exit_price_xrp: Optional[float] = Field(default=None)
    size_xrp: float
    stop_loss_pct: float
    take_profit_pct: float
    status: str = Field(default="OPEN")  # "OPEN" | "CLOSED_TP" | "CLOSED_SL" | "CLOSED_MANUAL"
    pnl_xrp: Optional[float] = Field(default=None)
    opened_at: datetime = Field(default_factory=_utcnow)
    closed_at: Optional[datetime] = Field(default=None)
