from __future__ import annotations
import json
from pathlib import Path
from sonic_xrpl.xaman_governance_review_export_manifest_audit_spec.models import ManifestAuditRecord,XamanGovernanceReviewExportManifestAuditFixtureInput

def _b(v): return v if isinstance(v,bool) else str(v).strip().lower() in {'1','true','yes'}
def _record(p): return ManifestAuditRecord(str(p.get('audit_record_id','')),str(p.get('audit_domain','')),str(p.get('source_manifest_id','')),str(p.get('source_artifact_id','')),str(p.get('source_phase_number','')),str(p.get('declared_source_reference','')),str(p.get('declared_content_hash','')),str(p.get('observed_content_hash','')),str(p.get('inclusion_status','')),str(p.get('redaction_status','')),str(p.get('reviewer_visibility','')),str(p.get('audit_status','')),str(p.get('finding_severity','')),str(p.get('limitation_notes','')),tuple(str(i) for i in p.get('safety_flags',[])))
def load_xaman_governance_review_export_manifest_audit_fixture(path:str|Path):
    p=json.loads(Path(path).read_text(encoding='utf-8-sig'))
    return XamanGovernanceReviewExportManifestAuditFixtureInput(str(p.get('fixture_id','')),str(p.get('audit_bundle_id','')),str(p.get('source_manifest_id','')),str(p.get('source_package_id','')),str(p.get('deterministic_timestamp','')),_b(p.get('manifest_present',False)),tuple(_record(i) for i in p.get('manifest_audit_records',[])),tuple(str(i) for i in p.get('reviewer_summary_types',[])),tuple(str(i) for i in p.get('limitation_ids',[])),tuple(str(i) for i in p.get('traceability_refs',[])),_b(p.get('hidden_expired_waiver',False)),_b(p.get('hidden_revoked_waiver',False)),_b(p.get('hidden_overdue_critical_sla',False)),_b(p.get('hidden_unsafe_waiver_attempt',False)),_b(p.get('invalid_xaman_payload_approval_marker',False)),_b(p.get('invalid_wallet_material_approval_marker',False)),_b(p.get('invalid_signing_submission_autofill_approval_marker',False)),_b(p.get('invalid_testnet_live_execution_approval_marker',False)),_b(p.get('invalid_runtime_manifest_audit_service_marker',False)),_b(p.get('invalid_download_service_marker',False)),_b(p.get('invalid_api_ui_audit_route_marker',False)),_b(p.get('invalid_safety_bypass_marker',False)))
