"""Report writer for market snapshots — Phase 47.

Outputs deterministic JSON reports to reports/phase47/.
No live calls. Read-only.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sonic_xrpl.market.models import MarketSnapshot


_REPORTS_DIR = Path("reports") / "phase47"


def _snapshot_to_dict(snapshot: MarketSnapshot) -> dict[str, Any]:
    """Convert a MarketSnapshot to a JSON-serialisable dict."""
    return asdict(snapshot)


def write_snapshot_report(
    snapshot: MarketSnapshot,
    output_dir: Path | str | None = None,
    *,
    filename_prefix: str = "market_snapshot",
) -> Path:
    """Write a MarketSnapshot to a JSON report file.

    Args:
        snapshot: The snapshot to write.
        output_dir: Directory to write to. Defaults to reports/phase47/.
        filename_prefix: Prefix for the output filename.

    Returns:
        Path to the written report file.
    """
    if output_dir is None:
        output_dir = _REPORTS_DIR
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    filename = f"{filename_prefix}_{snapshot.snapshot_id[:12]}_{timestamp}.json"
    out_path = output_dir / filename

    data = _snapshot_to_dict(snapshot)
    out_path.write_text(json.dumps(data, indent=2, ensure_ascii=True, default=str))
    return out_path


def write_snapshot_summary(
    snapshot: MarketSnapshot,
    output_dir: Path | str | None = None,
    *,
    filename_prefix: str = "market_snapshot_summary",
) -> Path:
    """Write a compact human-readable summary report.

    Returns:
        Path to the written summary file.
    """
    if output_dir is None:
        output_dir = _REPORTS_DIR
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    filename = f"{filename_prefix}_{snapshot.snapshot_id[:12]}_{timestamp}.md"
    out_path = output_dir / filename

    lines = [
        f"# Market Snapshot Report",
        f"",
        f"**Snapshot ID**: `{snapshot.snapshot_id}`",
        f"**Created at**: {snapshot.created_at}",
        f"**Fixture ID**: `{snapshot.fixture_id}`",
        f"**Ledger index**: {snapshot.ledger_index}",
        f"**Network**: {snapshot.network}",
        f"",
        f"## Quality",
        f"",
        f"- Score: **{snapshot.quality.score}/100**",
        f"- Recommendation: **{snapshot.quality.recommendation.value}**",
        f"",
    ]

    if snapshot.quality.missing_sections:
        lines.append(f"- Missing sections: {', '.join(snapshot.quality.missing_sections)}")

    if snapshot.quality.protocol_warnings:
        lines.append(f"")
        lines.append(f"### Protocol Warnings")
        for w in snapshot.quality.protocol_warnings:
            lines.append(f"- {w}")

    if snapshot.quality.fixture_warnings:
        lines.append(f"")
        lines.append(f"### Fixture Warnings")
        for w in snapshot.quality.fixture_warnings:
            lines.append(f"- {w}")

    lines += [
        f"",
        f"## Sections",
        f"",
        f"| Section | Count |",
        f"|---------|-------|",
        f"| Assets | {len(snapshot.assets)} |",
        f"| AMM pools | {len(snapshot.amms)} |",
        f"| Orderbooks | {len(snapshot.orderbooks)} |",
        f"| Accounts | {len(snapshot.accounts)} |",
        f"| Trustlines | {len(snapshot.trustlines)} |",
        f"| MPT holders | {len(snapshot.mpt_holders)} |",
        f"| Metadata signals | {len(snapshot.metadata_signals)} |",
        f"",
    ]

    if snapshot.limitations:
        lines.append(f"## Limitations")
        lines.append(f"")
        for lim in snapshot.limitations:
            lines.append(f"- {lim}")

    lines.append(f"")
    lines.append(f"---")
    lines.append(f"*Generated by Sonic XRPL Autotrader Phase 47 — offline, no live data*")

    out_path.write_text("\n".join(lines))
    return out_path
