from __future__ import annotations
import json
from pathlib import Path
from sonic_xrpl.xaman_governance_approval_packet_review_checklist_spec.models import *
def _b(v): return v if isinstance(v,bool) else str(v).strip().lower() in {'1','true','yes'}
def _item(p): return ChecklistItemRecord(str(p.get('checklist_item_id','')),str(p.get('checklist_domain','')),str(p.get('related_approval_packet_artifact_id','')),str(p.get('related_manifest_audit_id','')),str(p.get('related_export_package_id','')),tuple(str(i) for i in p.get('related_support_artifact_ids',[])),str(p.get('reviewer_role','')),str(p.get('required_evidence_reference','')),str(p.get('checklist_question','')),str(p.get('expected_safe_answer','')),str(p.get('actual_fixture_answer','')),str(p.get('checklist_status','')),str(p.get('finding_severity','')),str(p.get('limitation_notes','')),tuple(str(i) for i in p.get('safety_flags',[])))
def load_xaman_governance_approval_packet_review_checklist_fixture(path:str|Path):
    p=json.loads(Path(path).read_text(encoding='utf-8-sig'))
    return XamanGovernanceApprovalPacketReviewChecklistFixtureInput(str(p.get('fixture_id','')),str(p.get('checklist_bundle_id','')),str(p.get('source_approval_packet_id','')),str(p.get('source_manifest_audit_id','')),str(p.get('source_export_package_id','')),str(p.get('source_final_readiness_bundle_id','')),str(p.get('deterministic_timestamp','')),_b(p.get('approval_packet_present',False)),str(p.get('approval_packet_classification','')),_b(p.get('manifest_audit_present',False)),str(p.get('manifest_audit_classification','')),_b(p.get('export_package_present',False)),_b(p.get('final_readiness_bundle_present',False)),tuple(str(i) for i in p.get('reviewer_roles',[])),tuple(str(i) for i in p.get('non_authorization_notices',[])),tuple(_item(i) for i in p.get('checklist_items',[])),_b(p.get('hidden_unresolved_blocker',False)),_b(p.get('hidden_unresolved_limitation',False)),_b(p.get('expired_waiver_unresolved',False)),_b(p.get('revoked_waiver_unresolved',False)),_b(p.get('overdue_sla_unresolved',False)),_b(p.get('dependency_audit_unresolved',False)),_b(p.get('safety_review_unresolved',False)),_b(p.get('traceability_gap',False)),_b(p.get('ambiguous_non_authorization_wording',False)),_b(p.get('unsafe_waiver_attempt_unresolved',False)),_b(p.get('invalid_xaman_payload_approval_marker',False)),_b(p.get('invalid_wallet_material_approval_marker',False)),_b(p.get('invalid_signing_submission_autofill_approval_marker',False)),_b(p.get('invalid_testnet_live_execution_approval_marker',False)),_b(p.get('invalid_runtime_checklist_service_marker',False)),_b(p.get('invalid_download_service_marker',False)),_b(p.get('invalid_api_ui_checklist_route_marker',False)),_b(p.get('invalid_safety_bypass_marker',False)))
