from __future__ import annotations

ALLOWED_STATES: tuple[str, ...] = (
    "DRAFT_REVIEW",
    "AWAITING_OPERATOR_REVIEW",
    "OPERATOR_APPROVED_FOR_FUTURE_TESTNET",
    "OPERATOR_REJECTED",
    "EXPIRED",
    "CANCELLED",
    "CALLBACK_RECEIVED_SPEC_ONLY",
    "CALLBACK_VERIFICATION_REQUIRED",
    "CALLBACK_VERIFIED_SPEC_ONLY",
    "DUPLICATE_CALLBACK_REJECTED",
    "REPLAY_REJECTED",
    "STALE_CALLBACK_REJECTED",
    "AUDIT_REQUIRED",
    "FINAL_SPEC_ACCEPTED",
    "FINAL_SPEC_REJECTED",
)

FORBIDDEN_STATES: tuple[str, ...] = (
    "EXECUTED",
    "SIGNED",
    "SUBMITTED",
    "LIVE",
    "MAINNET_APPROVED",
    "AUTO_APPROVED",
)
