from __future__ import annotations
import json
from pathlib import Path
from sonic_xrpl.xaman_governance_closure_review_digest_spec.models import ClosureDigestSectionRecord,XamanGovernanceClosureReviewDigestFixtureInput

def _load_section(row:dict)->ClosureDigestSectionRecord:
    return ClosureDigestSectionRecord(row['closure_digest_section_id'],row['digest_domain'],row.get('related_closure_evidence_id',''),row.get('related_resolution_record_id',''),row.get('related_response_record_id',''),row.get('related_digest_id',''),row.get('related_snapshot_id',''),row.get('related_checklist_item_id',''),row.get('related_approval_packet_id',''),tuple(row.get('related_support_artifact_ids',[])),row.get('section_title',''),row.get('section_summary',''),int(row.get('evidence_count',0)),int(row.get('sufficient_evidence_count',0)),int(row.get('insufficient_evidence_count',0)),int(row.get('blocker_count',0)),int(row.get('limitation_count',0)),row.get('reviewer_visibility',''),row.get('digest_status','CLOSURE_DIGEST_NOT_STARTED'),row.get('severity','MEDIUM'),row.get('limitation_notes',''),tuple(row.get('safety_flags',[])))

def load_xaman_governance_closure_review_digest_fixture(path:str|Path)->XamanGovernanceClosureReviewDigestFixtureInput:
    p=Path(path); data=json.loads(p.read_text(encoding='utf-8')); sections=tuple(_load_section(i) for i in data.get('closure_digest_sections',[]))
    return XamanGovernanceClosureReviewDigestFixtureInput(data['fixture_id'],data['closure_digest_bundle_id'],data['source_closure_bundle_id'],data.get('source_resolution_register_id',''),data.get('deterministic_timestamp','1970-01-01T00:00:00Z'),bool(data.get('closure_bundle_present',False)),data.get('closure_bundle_classification','CLOSURE_BUNDLE_REVIEW_REQUIRED'),data.get('resolution_register_classification','RESOLUTION_REGISTER_REVIEW_REQUIRED'),tuple(data.get('non_authorization_notices',[])),bool(data.get('reviewer_ownership_summary_present',False)),sections,bool(data.get('missing_closure_evidence_summary',False)),bool(data.get('missing_resolution_register_summary',False)),bool(data.get('missing_response_summary',False)),bool(data.get('missing_digest_snapshot_checklist_summary',False)),bool(data.get('hidden_unresolved_blocker',False)),bool(data.get('hidden_unresolved_limitation',False)),bool(data.get('dependency_audit_closure_summary_gap',False)),bool(data.get('safety_review_closure_summary_gap',False)),bool(data.get('traceability_gap',False)),bool(data.get('stale_closure_evidence_summary_gap',False)),bool(data.get('redacted_closure_evidence_summary_gap',False)),bool(data.get('reference_only_closure_evidence_summary_gap',False)),bool(data.get('synthetic_only_closure_evidence_summary_gap',False)),bool(data.get('missing_non_authorization_summary',False)),bool(data.get('invalid_xaman_payload_approval_marker',False)),bool(data.get('invalid_wallet_material_approval_marker',False)),bool(data.get('invalid_signing_submission_autofill_approval_marker',False)),bool(data.get('invalid_testnet_live_execution_approval_marker',False)),bool(data.get('invalid_runtime_closure_digest_service_marker',False)),bool(data.get('invalid_download_service_marker',False)),bool(data.get('invalid_api_ui_closure_digest_route_marker',False)),bool(data.get('invalid_safety_bypass_marker',False)))
