from __future__ import annotations
import json
from pathlib import Path
from sonic_xrpl.xaman_governance_review_export_approval_packet_spec.models import *
def _b(v): return v if isinstance(v,bool) else str(v).strip().lower() in {'1','true','yes'}
def _art(p): return ApprovalArtifactReference(str(p.get('approval_artifact_id','')),str(p.get('source_phase_number','')),str(p.get('source_artifact_type','')),str(p.get('source_reference','')),str(p.get('source_hash','')),str(p.get('required_classification','')),str(p.get('inclusion_status','')),str(p.get('audit_status','')),str(p.get('limitation_notes','')),tuple(str(i) for i in p.get('safety_flags',[])))
def _ack(p): return ReviewerAcknowledgementRecord(str(p.get('acknowledgement_id','')),str(p.get('reviewer_role','')),str(p.get('reviewer_domain','')),str(p.get('related_artifact_id','')),str(p.get('acknowledgement_status','')),str(p.get('acknowledgement_limitation','')),str(p.get('non_authorization_statement','')),tuple(str(i) for i in p.get('required_evidence_references',[])),tuple(str(i) for i in p.get('safety_flags',[])))
def load_xaman_governance_review_export_approval_packet_fixture(path:str|Path):
    p=json.loads(Path(path).read_text(encoding='utf-8-sig'))
    return XamanGovernanceReviewExportApprovalPacketFixtureInput(str(p.get('fixture_id','')),str(p.get('approval_packet_id','')),str(p.get('source_export_package_id','')),str(p.get('source_manifest_audit_id','')),str(p.get('deterministic_timestamp','')),_b(p.get('export_package_present',False)),_b(p.get('manifest_audit_present',False)),str(p.get('export_classification','')),str(p.get('manifest_audit_classification','')),tuple(_art(i) for i in p.get('artifact_references',[])),tuple(_ack(i) for i in p.get('reviewer_acknowledgements',[])),_b(p.get('unresolved_blocker_hidden',False)),_b(p.get('unresolved_limitation_hidden',False)),_b(p.get('expired_waiver_unresolved',False)),_b(p.get('revoked_waiver_unresolved',False)),_b(p.get('overdue_sla_unresolved',False)),_b(p.get('unsafe_waiver_attempt_unresolved',False)),_b(p.get('dependency_audit_unresolved',False)),_b(p.get('safety_review_unresolved',False)),_b(p.get('invalid_xaman_payload_approval_marker',False)),_b(p.get('invalid_wallet_material_approval_marker',False)),_b(p.get('invalid_signing_submission_autofill_approval_marker',False)),_b(p.get('invalid_testnet_live_execution_approval_marker',False)),_b(p.get('invalid_runtime_approval_service_marker',False)),_b(p.get('invalid_download_service_marker',False)),_b(p.get('invalid_api_ui_approval_route_marker',False)),_b(p.get('invalid_safety_bypass_marker',False)))
