from __future__ import annotations
import json
from pathlib import Path
from sonic_xrpl.xaman_governance_approval_checklist_evidence_snapshot_spec.models import *
def _b(v): return v if isinstance(v,bool) else str(v).strip().lower() in {'1','true','yes'}
def _rec(p): return SnapshotEvidenceRecord(str(p.get('snapshot_evidence_id','')),str(p.get('snapshot_domain','')),str(p.get('related_checklist_item_id','')),str(p.get('related_approval_packet_artifact_id','')),str(p.get('related_manifest_audit_id','')),str(p.get('related_export_package_id','')),tuple(str(i) for i in p.get('related_support_artifact_ids',[])),str(p.get('evidence_source_reference','')),str(p.get('evidence_kind','')),str(p.get('evidence_hash','')),str(p.get('evidence_status','')),str(p.get('snapshot_inclusion_status','')),str(p.get('limitation_notes','')),tuple(str(i) for i in p.get('safety_flags',[])))
def load_xaman_governance_approval_checklist_evidence_snapshot_fixture(path:str|Path):
    p=json.loads(Path(path).read_text(encoding='utf-8-sig'))
    return XamanGovernanceApprovalChecklistEvidenceSnapshotFixtureInput(str(p.get('fixture_id','')),str(p.get('snapshot_bundle_id','')),str(p.get('source_checklist_id','')),str(p.get('source_approval_packet_id','')),str(p.get('source_manifest_audit_id','')),str(p.get('source_export_package_id','')),str(p.get('source_final_readiness_bundle_id','')),str(p.get('deterministic_timestamp','')),_b(p.get('checklist_present',False)),str(p.get('checklist_classification','')),_b(p.get('approval_packet_present',False)),str(p.get('approval_packet_classification','')),_b(p.get('manifest_audit_present',False)),_b(p.get('export_package_present',False)),_b(p.get('final_readiness_bundle_present',False)),tuple(str(i) for i in p.get('non_authorization_notices',[])),_b(p.get('reviewer_acknowledgement_present',False)),tuple(_rec(i) for i in p.get('snapshot_evidence_records',[])),_b(p.get('hidden_unresolved_blocker',False)),_b(p.get('hidden_unresolved_limitation',False)),_b(p.get('expired_waiver_unresolved',False)),_b(p.get('revoked_waiver_unresolved',False)),_b(p.get('overdue_sla_unresolved',False)),_b(p.get('dependency_audit_unresolved',False)),_b(p.get('safety_review_unresolved',False)),_b(p.get('traceability_gap',False)),_b(p.get('stale_evidence',False)),_b(p.get('redacted_evidence_requires_review',False)),_b(p.get('reference_only_evidence_missing_limitation',False)),_b(p.get('synthetic_only_evidence_requires_review',False)),_b(p.get('unsafe_waiver_attempt_unresolved',False)),_b(p.get('invalid_xaman_payload_approval_marker',False)),_b(p.get('invalid_wallet_material_approval_marker',False)),_b(p.get('invalid_signing_submission_autofill_approval_marker',False)),_b(p.get('invalid_testnet_live_execution_approval_marker',False)),_b(p.get('invalid_runtime_snapshot_service_marker',False)),_b(p.get('invalid_download_service_marker',False)),_b(p.get('invalid_api_ui_snapshot_route_marker',False)),_b(p.get('invalid_safety_bypass_marker',False)))
