from __future__ import annotations
from sonic_xrpl.xaman_governance_approval_checklist_evidence_snapshot_spec.models import *
def build_xaman_governance_approval_checklist_evidence_snapshot_spec(row:XamanGovernanceApprovalChecklistEvidenceSnapshotFixtureInput):
    errors=[]; blockers=[]; findings=[]; limits=[]
    def add(i,c,s,rel,summary,block=False):
        findings.append(SnapshotFindingRecord(i,c,rel,s,summary)); limits.append(SnapshotLimitationRecord(i,c,rel,s,summary)); (blockers if block else errors).append(i)
    if not row.checklist_present: add('missing_checklist_evidence','MISSING_CHECKLIST_EVIDENCE','HIGH','checklist','missing checklist evidence')
    elif row.checklist_classification!='CHECKLIST_SPEC_REVIEW_READY': add('checklist_not_spec_ready','CHECKLIST_NOT_SPEC_READY','HIGH','checklist','checklist not spec-review-ready')
    if not row.approval_packet_present: add('missing_approval_packet_evidence','MISSING_APPROVAL_PACKET_EVIDENCE','HIGH','approval-packet','missing approval packet evidence')
    if not row.manifest_audit_present: add('missing_manifest_audit_evidence','MISSING_MANIFEST_AUDIT_EVIDENCE','HIGH','manifest-audit','missing manifest audit evidence')
    if not row.export_package_present: add('missing_export_package_evidence','MISSING_EXPORT_PACKAGE_EVIDENCE','HIGH','export-package','missing export package evidence')
    if not row.final_readiness_bundle_present: add('missing_final_readiness_evidence','MISSING_FINAL_READINESS_EVIDENCE','HIGH','final-readiness-bundle','missing final readiness evidence')
    if not row.reviewer_acknowledgement_present: add('missing_reviewer_acknowledgement_evidence','MISSING_REVIEWER_ACKNOWLEDGEMENT_EVIDENCE','HIGH','acknowledgements','missing reviewer acknowledgement evidence')
    notices=set(row.non_authorization_notices)
    for notice in REQUIRED_NOTICES:
        if notice not in notices: add('missing_notice_'+notice.replace(' ','_').replace('/','_'),'MISSING_NON_AUTHORIZATION_NOTICE_EVIDENCE','HIGH',notice,'missing non-authorization notice evidence')
    for rec in row.snapshot_evidence_records:
        if rec.evidence_status in {'EVIDENCE_MISSING','EVIDENCE_BLOCKED'}: add('record_'+rec.snapshot_evidence_id,'MISSING_SNAPSHOT_EVIDENCE','HIGH',rec.snapshot_evidence_id,'snapshot evidence missing or blocked',rec.evidence_status=='EVIDENCE_BLOCKED')
        elif rec.evidence_status in {'EVIDENCE_STALE','EVIDENCE_REFERENCE_ONLY','EVIDENCE_SYNTHETIC_ONLY','EVIDENCE_REDACTED','EVIDENCE_UNVERIFIED'}: add('record_'+rec.snapshot_evidence_id,'SNAPSHOT_EVIDENCE_REVIEW_REQUIRED','MEDIUM',rec.snapshot_evidence_id,'snapshot evidence requires review')
    for active,i,c,s,b in [(row.stale_evidence,'stale_evidence','STALE_EVIDENCE','MEDIUM',False),(row.redacted_evidence_requires_review,'redacted_evidence_requires_review','REDACTED_EVIDENCE_REQUIRES_REVIEW','MEDIUM',False),(row.reference_only_evidence_missing_limitation,'reference_only_evidence_missing_limitation','REFERENCE_ONLY_EVIDENCE_MISSING_LIMITATION','HIGH',False),(row.synthetic_only_evidence_requires_review,'synthetic_only_evidence_requires_review','SYNTHETIC_ONLY_EVIDENCE_REQUIRES_REVIEW','MEDIUM',False),(row.hidden_unresolved_blocker,'hidden_unresolved_blocker','UNRESOLVED_BLOCKER_HIDDEN','HIGH',False),(row.hidden_unresolved_limitation,'hidden_unresolved_limitation','UNRESOLVED_LIMITATION_HIDDEN','MEDIUM',False),(row.expired_waiver_unresolved,'expired_waiver_unresolved','EXPIRED_WAIVER_UNRESOLVED','HIGH',False),(row.revoked_waiver_unresolved,'revoked_waiver_unresolved','REVOKED_WAIVER_UNRESOLVED','HIGH',False),(row.overdue_sla_unresolved,'overdue_sla_unresolved','OVERDUE_SLA_UNRESOLVED','CRITICAL',True),(row.dependency_audit_unresolved,'dependency_audit_unresolved','DEPENDENCY_AUDIT_EVIDENCE_UNRESOLVED','HIGH',False),(row.safety_review_unresolved,'safety_review_unresolved','SAFETY_REVIEW_EVIDENCE_UNRESOLVED','HIGH',False),(row.traceability_gap,'traceability_gap','TRACEABILITY_GAP','HIGH',False),(row.unsafe_waiver_attempt_unresolved,'unsafe_waiver_attempt_unresolved','UNSAFE_WAIVER_ATTEMPT_UNRESOLVED','CRITICAL',True)]:
        if active: add(i,c,s,i,i.replace('_',' '),b)
    for active,i,c in [(row.invalid_xaman_payload_approval_marker,'xaman_payload_approval_wording','XAMAN_PAYLOAD_APPROVAL_WORDING'),(row.invalid_wallet_material_approval_marker,'wallet_material_approval_wording','WALLET_MATERIAL_APPROVAL_WORDING'),(row.invalid_signing_submission_autofill_approval_marker,'signing_submission_autofill_approval_wording','SIGNING_SUBMISSION_AUTOFILL_APPROVAL_WORDING'),(row.invalid_testnet_live_execution_approval_marker,'testnet_live_execution_approval_wording','TESTNET_LIVE_EXECUTION_APPROVAL_WORDING'),(row.invalid_runtime_snapshot_service_marker,'runtime_snapshot_service_marker','RUNTIME_SNAPSHOT_SERVICE_MARKER'),(row.invalid_download_service_marker,'download_service_marker','DOWNLOAD_SERVICE_MARKER'),(row.invalid_api_ui_snapshot_route_marker,'api_ui_snapshot_route_marker','API_UI_SNAPSHOT_ROUTE_MARKER'),(row.invalid_safety_bypass_marker,'safety_bypass_marker','SAFETY_BYPASS_MARKER')]:
        if active: add(i,c,'CRITICAL',i,c,True)
    if blockers: cls=SNAPSHOT_BLOCKED
    elif not row.checklist_present or not row.approval_packet_present or not row.manifest_audit_present or not row.export_package_present or not row.final_readiness_bundle_present: cls=SNAPSHOT_INCOMPLETE
    elif errors: cls=SNAPSHOT_REVIEW_REQUIRED if len(errors)<4 else SNAPSHOT_NOT_READY
    else: cls=SNAPSHOT_SPEC_REVIEW_READY
    spec=XamanGovernanceApprovalChecklistEvidenceSnapshotSpec('80','Xaman governance approval checklist evidence snapshot contract spec',row.snapshot_bundle_id,row.source_checklist_id,row.source_approval_packet_id,row.deterministic_timestamp,SNAPSHOT_DOMAINS,row.snapshot_evidence_records,tuple(findings),tuple(limits),REQUIRED_NOTICES)
    return XamanGovernanceApprovalChecklistEvidenceSnapshotReport(row.fixture_id,spec,cls,tuple(errors+blockers),tuple(blockers))
