from __future__ import annotations
import json
from pathlib import Path
from sonic_xrpl.xaman_governance_snapshot_review_digest_spec.models import *
def _b(v): return v if isinstance(v,bool) else str(v).strip().lower() in {'1','true','yes'}
def _sec(p): return DigestSectionRecord(str(p.get('digest_section_id','')),str(p.get('digest_domain','')),str(p.get('related_snapshot_record_id','')),str(p.get('related_checklist_item_id','')),str(p.get('related_approval_packet_id','')),tuple(str(i) for i in p.get('related_support_artifact_ids',[])),str(p.get('section_title','')),str(p.get('section_summary','')),int(p.get('evidence_count',0)),int(p.get('blocker_count',0)),int(p.get('limitation_count',0)),str(p.get('reviewer_visibility','')),str(p.get('digest_status','')),str(p.get('severity','')),str(p.get('limitation_notes','')),tuple(str(i) for i in p.get('safety_flags',[])))
def load_xaman_governance_snapshot_review_digest_fixture(path:str|Path):
    p=json.loads(Path(path).read_text(encoding='utf-8-sig'))
    return XamanGovernanceSnapshotReviewDigestFixtureInput(str(p.get('fixture_id','')),str(p.get('digest_bundle_id','')),str(p.get('source_snapshot_id','')),str(p.get('source_checklist_id','')),str(p.get('source_approval_packet_id','')),str(p.get('deterministic_timestamp','')),_b(p.get('snapshot_present',False)),str(p.get('snapshot_classification','')),_b(p.get('checklist_present',False)),str(p.get('checklist_classification','')),tuple(str(i) for i in p.get('non_authorization_notices',[])),_b(p.get('reviewer_ack_summary_present',False)),tuple(_sec(i) for i in p.get('digest_sections',[])),_b(p.get('hidden_unresolved_blocker',False)),_b(p.get('hidden_unresolved_limitation',False)),_b(p.get('dependency_audit_summary_gap',False)),_b(p.get('safety_review_summary_gap',False)),_b(p.get('traceability_gap',False)),_b(p.get('stale_evidence_summary_gap',False)),_b(p.get('redacted_evidence_summary_gap',False)),_b(p.get('reference_only_evidence_summary_gap',False)),_b(p.get('synthetic_only_evidence_summary_gap',False)),_b(p.get('invalid_xaman_payload_approval_marker',False)),_b(p.get('invalid_wallet_material_approval_marker',False)),_b(p.get('invalid_signing_submission_autofill_approval_marker',False)),_b(p.get('invalid_testnet_live_execution_approval_marker',False)),_b(p.get('invalid_runtime_digest_service_marker',False)),_b(p.get('invalid_download_service_marker',False)),_b(p.get('invalid_api_ui_digest_route_marker',False)),_b(p.get('invalid_safety_bypass_marker',False)))
