from __future__ import annotations
import json
from pathlib import Path
from sonic_xrpl.xaman_governance_response_resolution_register_spec.models import ResolutionRecord,XamanGovernanceResponseResolutionRegisterFixtureInput

def _load_resolution_record(row:dict)->ResolutionRecord:
    return ResolutionRecord(row['resolution_id'],row['resolution_domain'],row.get('related_response_record_id',''),row.get('related_digest_id',''),row.get('related_snapshot_id',''),row.get('related_checklist_item_id',''),row.get('related_approval_packet_id',''),tuple(row.get('related_support_artifact_ids',[])),row.get('owner_role',''),row.get('resolution_category','RESOLUTION_REVIEW_REQUIRED'),row.get('resolution_status','RESOLUTION_NOT_STARTED'),row.get('resolution_summary',''),tuple(row.get('follow_up_evidence_references',[])),tuple(row.get('unresolved_blocker_references',[])),tuple(row.get('unresolved_limitation_references',[])),bool(row.get('non_authorization_confirmation',False)),row.get('closure_condition','NO_RUNTIME_ACTION'),row.get('deferral_reason',''),row.get('rejection_reason',''),row.get('superseded_by_resolution_id',''),row.get('severity','MEDIUM'),row.get('limitation_notes',''),tuple(row.get('safety_flags',[])))

def load_xaman_governance_response_resolution_register_fixture(path:str|Path)->XamanGovernanceResponseResolutionRegisterFixtureInput:
    p=Path(path); data=json.loads(p.read_text(encoding='utf-8')); records=tuple(_load_resolution_record(i) for i in data.get('resolution_records',[]))
    return XamanGovernanceResponseResolutionRegisterFixtureInput(data['fixture_id'],data['resolution_register_id'],data['source_response_bundle_id'],data['source_digest_bundle_id'],data.get('deterministic_timestamp','1970-01-01T00:00:00Z'),data.get('response_classification','RESPONSE_BUNDLE_REVIEW_REQUIRED'),data.get('digest_classification','DIGEST_REVIEW_REQUIRED'),records,tuple(data.get('non_authorization_notices',[])),bool(data.get('missing_resolution_record',False)),bool(data.get('incomplete_resolution_record',False)),bool(data.get('rejected_resolution_unresolved',False)),bool(data.get('deferred_blocker_without_limitation',False)),bool(data.get('superseded_resolution_missing_replacement',False)),bool(data.get('missing_non_authorization_confirmation',False)),bool(data.get('missing_owner',False)),bool(data.get('missing_follow_up_evidence_reference',False)),bool(data.get('unresolved_blocker_lacks_resolution',False)),bool(data.get('unresolved_limitation_lacks_resolution',False)),bool(data.get('stale_evidence_resolution_unresolved',False)),bool(data.get('redacted_evidence_resolution_unresolved',False)),bool(data.get('reference_only_evidence_resolution_unresolved',False)),bool(data.get('synthetic_only_evidence_resolution_unresolved',False)),bool(data.get('dependency_audit_resolution_unresolved',False)),bool(data.get('safety_review_resolution_unresolved',False)),bool(data.get('traceability_gap',False)),bool(data.get('invalid_xaman_payload_approval_marker',False)),bool(data.get('invalid_wallet_material_approval_marker',False)),bool(data.get('invalid_signing_submission_autofill_approval_marker',False)),bool(data.get('invalid_testnet_live_execution_approval_marker',False)),bool(data.get('invalid_runtime_resolution_service_marker',False)),bool(data.get('invalid_download_service_marker',False)),bool(data.get('invalid_api_ui_resolution_route_marker',False)),bool(data.get('invalid_safety_bypass_marker',False)))
