from __future__ import annotations
import json
from pathlib import Path
from sonic_xrpl.xaman_governance_digest_review_response_spec.models import ResponseRecord,XamanGovernanceDigestReviewResponseFixtureInput

def _load_response_record(row:dict)->ResponseRecord:
    return ResponseRecord(row['response_id'],row['response_domain'],row.get('related_digest_id',''),row.get('related_snapshot_id',''),row.get('related_checklist_item_id',''),row.get('related_approval_packet_id',''),tuple(row.get('related_support_artifact_ids',[])),row.get('reviewer_role',''),row.get('response_category',''),row.get('response_summary',''),row.get('follow_up_evidence_reference',''),row.get('resolution_intent','NO_RUNTIME_ACTION'),bool(row.get('non_authorization_confirmation',False)),row.get('response_status','RESPONSE_NOT_STARTED'),row.get('severity','MEDIUM'),row.get('limitation_notes',''),tuple(row.get('safety_flags',[])))

def load_xaman_governance_digest_review_response_fixture(path:str|Path)->XamanGovernanceDigestReviewResponseFixtureInput:
    p=Path(path); data=json.loads(p.read_text(encoding='utf-8')); records=tuple(_load_response_record(i) for i in data.get('response_records',[]))
    return XamanGovernanceDigestReviewResponseFixtureInput(data['fixture_id'],data['response_bundle_id'],data['source_digest_bundle_id'],data['source_snapshot_id'],data.get('deterministic_timestamp','1970-01-01T00:00:00Z'),data.get('digest_classification','DIGEST_REVIEW_REQUIRED'),data.get('snapshot_classification','SNAPSHOT_REVIEW_REQUIRED'),records,tuple(data.get('non_authorization_notices',[])),bool(data.get('missing_digest_response',False)),bool(data.get('incomplete_digest_response',False)),bool(data.get('rejected_digest_response',False)),bool(data.get('deferred_blocker_without_limitation',False)),bool(data.get('missing_non_authorization_confirmation',False)),bool(data.get('missing_security_reviewer_response',False)),bool(data.get('missing_follow_up_evidence_reference',False)),bool(data.get('unresolved_blocker_lacks_response',False)),bool(data.get('unresolved_limitation_lacks_response',False)),bool(data.get('stale_evidence_response_unresolved',False)),bool(data.get('redacted_evidence_response_unresolved',False)),bool(data.get('reference_only_evidence_response_unresolved',False)),bool(data.get('synthetic_only_evidence_response_unresolved',False)),bool(data.get('dependency_audit_response_unresolved',False)),bool(data.get('safety_review_response_unresolved',False)),bool(data.get('traceability_gap',False)),bool(data.get('invalid_xaman_payload_approval_marker',False)),bool(data.get('invalid_wallet_material_approval_marker',False)),bool(data.get('invalid_signing_submission_autofill_approval_marker',False)),bool(data.get('invalid_testnet_live_execution_approval_marker',False)),bool(data.get('invalid_runtime_response_service_marker',False)),bool(data.get('invalid_download_service_marker',False)),bool(data.get('invalid_api_ui_response_route_marker',False)),bool(data.get('invalid_safety_bypass_marker',False)))
